"use client";

import { useCallback, useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  FileDown,
  ClipboardCopy,
  Check,
  Printer,
  FileText,
  ShieldCheck,
  TrendingUp,
  Layout,
  BookOpen,
  AlertTriangle,
  Sparkles,
} from "lucide-react";
import type { Message, SourceCitation } from "@/lib/types";
import { cn } from "@/lib/utils";

type ReportTemplate = "executive" | "technical" | "swot";

interface ReportGeneratorProps {
  query: string;
  messages: Message[];
  sources: SourceCitation[];
}

interface TemplateConfig {
  key: ReportTemplate;
  label: string;
  icon: typeof FileText;
  description: string;
}

const TEMPLATES: TemplateConfig[] = [
  { key: "executive", label: "Executive Summary", icon: BookOpen, description: "Concise overview with key findings and recommendations" },
  { key: "technical", label: "Technical Report", icon: Layout, description: "Deep dive with methodology, analysis, and appendix" },
  { key: "swot", label: "SWOT Analysis", icon: TrendingUp, description: "Strengths, weaknesses, opportunities, and threats" },
];

function findAnswer(messages: Message[]): string {
  const answer = messages.find((m) => m.role === "assistant" && m.content !== "Thinking..." && m.content !== "...");
  return answer?.content || "";
}

function extractSections(text: string): { heading: string; content: string }[] {
  const sections: { heading: string; content: string }[] = [];
  const lines = text.split("\n");
  let current: { heading: string; content: string[] } | null = null;

  for (const line of lines) {
    const headingMatch = line.match(/^#{1,3}\s+(.+)/);
    if (headingMatch) {
      if (current) sections.push({ heading: current.heading, content: current.content.join("\n").trim() });
      current = { heading: headingMatch[1], content: [] };
    } else if (current) {
      current.content.push(line);
    }
  }
  if (current) sections.push({ heading: current.heading, content: current.content.join("\n").trim() });

  return sections;
}

function generateCoverPage(query: string): string {
  return [
    `<div style="page-break-after:always;text-align:center;padding-top:120px;">`,
    `<h1 style="font-size:2.5em;margin-bottom:8px;background:linear-gradient(135deg,#6366f1,#06b6d4);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;">${query}</h1>`,
    `<p style="font-size:1.1em;color:#64748b;margin-bottom:40px;">Research Report</p>`,
    `<hr style="width:80px;margin:0 auto 32px;border:none;height:2px;background:linear-gradient(90deg,#6366f1,#06b6d4);"/>`,
    `<p style="color:#94a3b8;font-size:0.85em;">Generated by ResearchSwarm AI</p>`,
    `<p style="color:#94a3b8;font-size:0.85em;">${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>`,
    `</div>`,
  ].join("\n");
}

function generateTOC(sections: { heading: string; content: string }[]): string {
  if (sections.length === 0) return "";
  const items = sections.map((s, i) =>
    `<li style="margin:4px 0;"><a href="#section-${i}" style="color:#8b5cf6;text-decoration:none;">${s.heading}</a></li>`
  ).join("\n");
  return [
    `<div style="page-break-after:always;">`,
    `<h2 style="font-size:1.6em;margin-bottom:16px;">Table of Contents</h2>`,
    `<ol style="list-style:none;padding:0;">${items}</ol>`,
    `</div>`,
  ].join("\n");
}

function generateExecutiveMD(query: string, answer: string, sources: SourceCitation[]): string {
  const sections = extractSections(answer);
  const firstLines = answer.split("\n").filter((l) => l.trim()).slice(0, 5).join(" ");

  const parts: string[] = [];
  parts.push(`# Research Report: ${query}`);
  parts.push("");
  parts.push(`> **Date:** ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
  parts.push(`> **Type:** Executive Summary`);
  parts.push(`> **Sources cited:** ${sources.length}`);
  parts.push("");
  parts.push("## Key Findings");
  parts.push("");
  parts.push(firstLines.slice(0, 500));
  parts.push("");

  if (sections.length > 0) {
    parts.push("## Section Overview");
    parts.push("");
    for (const s of sections) {
      parts.push(`- **${s.heading}** — ${s.content.slice(0, 120).replace(/\n/g, " ")}...`);
    }
    parts.push("");
  }

  if (sources.length > 0) {
    parts.push("## Sources");
    parts.push("");
    for (const source of sources) {
      parts.push(`- [${source.title}](${source.url || "#"})`);
    }
  }

  return parts.join("\n");
}

function generateTechnicalMD(query: string, answer: string, sources: SourceCitation[]): string {
  const sections = extractSections(answer);
  const parts: string[] = [];

  parts.push(`# Technical Report: ${query}`);
  parts.push("");
  parts.push(`**Date:** ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
  parts.push(`**Generator:** ResearchSwarm AI`);
  parts.push(`**Sources:** ${sources.length}`);
  parts.push("");

  if (sections.length > 0) {
    parts.push("## Table of Contents");
    for (const [i, s] of sections.entries()) {
      parts.push(`${i + 1}. [${s.heading}](#section-${i})`);
    }
    parts.push("");
  }

  for (const [i, s] of sections.entries()) {
    parts.push(`<a id="section-${i}"></a>`);
    parts.push(`## ${i + 1}. ${s.heading}`);
    parts.push("");
    parts.push(s.content);
    parts.push("");
  }

  if (sources.length > 0) {
    parts.push("## Appendix A: Sources");
    parts.push("");
    for (const [i, source] of sources.entries()) {
      parts.push(`${i + 1}. [${source.title}](${source.url || "#"})`);
    }
    parts.push("");
  }

  parts.push("## Appendix B: Methodology");
  parts.push("");
  parts.push("This report was generated using ResearchSwarm, a multi-agent AI research system.");
  parts.push("The system employs specialized agents for planning, web research, document analysis, and answer synthesis.");
  parts.push("Sources are scored by domain authority, freshness, and relevance.");

  return parts.join("\n");
}

function generateSWOTMD(query: string, answer: string, sources: SourceCitation[]): string {
  const sections = extractSections(answer);
  const fullText = answer.toLowerCase();

  const strengths = sections.filter((s) =>
    /advantage|benefit|strength|strong|effective|improvement|success|leading/i.test(s.content)
  ).map((s) => s.heading);
  const weaknesses = sections.filter((s) =>
    /limitation|challenge|weakness|drawback|concern|issue|gap|lack/i.test(s.content)
  ).map((s) => s.heading);
  const opportunities = sections.filter((s) =>
    /opportunity|potential|future|emerging|growth|trend|innovation/i.test(s.content)
  ).map((s) => s.heading);
  const threats = sections.filter((s) =>
    /risk|threat|danger|competition|regulatory|barrier|concern/i.test(s.content)
  ).map((s) => s.heading);

  const parts: string[] = [];
  parts.push(`# SWOT Analysis: ${query}`);
  parts.push("");
  parts.push(`**Date:** ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
  parts.push("");

  parts.push("## Strengths");
  parts.push("");
  if (strengths.length > 0) {
    for (const s of strengths) parts.push(`- ${s}`);
  } else {
    parts.push("*No explicit strengths identified in the source material.*");
  }
  parts.push("");

  parts.push("## Weaknesses");
  parts.push("");
  if (weaknesses.length > 0) {
    for (const s of weaknesses) parts.push(`- ${s}`);
  } else {
    parts.push("*No explicit weaknesses identified in the source material.*");
  }
  parts.push("");

  parts.push("## Opportunities");
  parts.push("");
  if (opportunities.length > 0) {
    for (const s of opportunities) parts.push(`- ${s}`);
  } else {
    parts.push("*No explicit opportunities identified in the source material.*");
  }
  parts.push("");

  parts.push("## Threats");
  parts.push("");
  if (threats.length > 0) {
    for (const s of threats) parts.push(`- ${s}`);
  } else {
    parts.push("*No explicit threats identified in the source material.*");
  }
  parts.push("");

  parts.push("---");
  parts.push("");
  parts.push("### Full Analysis");
  parts.push("");
  parts.push(answer);
  parts.push("");

  if (sources.length > 0) {
    parts.push("## Sources");
    parts.push("");
    for (const source of sources) {
      parts.push(`- [${source.title}](${source.url || "#"})`);
    }
  }

  return parts.join("\n");
}

function generateHTML(md: string, query: string, includeCover: boolean, includeTOC: boolean): string {
  const sections = extractSections(md);
  const bodyParts: string[] = [];

  if (includeCover) {
    bodyParts.push(generateCoverPage(query));
  }

  if (includeTOC && sections.length > 0) {
    bodyParts.push(generateTOC(sections));
  }

  bodyParts.push(
    `<div style="max-width:800px;margin:0 auto;padding:20px;">${
      md.split("\n").map((line) => {
        if (line.startsWith("# ")) return `<h1 id="${line.slice(2).toLowerCase().replace(/\s+/g, "-")}">${line.slice(2)}</h1>`;
        if (line.startsWith("## ")) return `<h2 id="${line.slice(3).toLowerCase().replace(/\s+/g, "-")}">${line.slice(3)}</h2>`;
        if (line.startsWith("### ")) return `<h3>${line.slice(4)}</h3>`;
        if (line.startsWith("> **")) return `<blockquote style="border-left:3px solid #8b5cf6;padding-left:12px;margin:8px 0;color:#64748b;">${line.slice(2)}</blockquote>`;
        if (line.startsWith("> ")) return `<blockquote style="border-left:3px solid #8b5cf6;padding-left:12px;margin:8px 0;color:#64748b;">${line.slice(2)}</blockquote>`;
        if (line.startsWith("- **") && line.includes("** —")) return `<li style="margin:4px 0;"><strong>${line.slice(4).split("** —")[0]}</strong> — ${line.split("** —")[1]}</li>`;
        if (line.startsWith("- ")) return `<li style="margin:4px 0;">${line.slice(2)}</li>`;
        if (line.startsWith("1. ")) return `<li style="margin:4px 0;">${line.slice(3)}</li>`;
        if (line.startsWith(`${sections.length + 1}. `)) return `<li style="margin:4px 0;">${line.slice(3)}</li>`;
        if (line.startsWith("*")) return `<em>${line.slice(1, -1)}</em>`;
        if (line.startsWith("---")) return `<hr style="margin:24px 0;border:none;border-top:1px solid #e2e8f0;" />`;
        if (line === "") return `<br/>`;
        return `<p style="line-height:1.7;margin:8px 0;">${line}</p>`;
      }).join("\n")
    }</div>`
  );

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Research Report: ${query}</title>
  <style>
    @page { margin: 20mm; }
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; color: #1a1a2e; background: #fff; }
    h1 { font-size: 2em; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px; margin-top: 32px; }
    h2 { font-size: 1.4em; margin-top: 28px; color: #1e293b; }
    h3 { font-size: 1.15em; margin-top: 20px; color: #334155; }
    a { color: #8b5cf6; }
    @media print { body { padding: 0; } }
  </style>
</head>
<body>${bodyParts.join("\n")}</body>
</html>`;
}

export default function ReportGenerator({ query, messages, sources }: ReportGeneratorProps) {
  const [copied, setCopied] = useState(false);
  const [template, setTemplate] = useState<ReportTemplate>("executive");
  const [includeCover, setIncludeCover] = useState(true);
  const [includeToc, setIncludeToc] = useState(true);
  const [showOptions, setShowOptions] = useState(false);

  const answer = useMemo(() => findAnswer(messages), [messages]);
  const hasAnswer = answer.length > 0;

  const md = useMemo(() => {
    switch (template) {
      case "executive": return generateExecutiveMD(query, answer, sources);
      case "technical": return generateTechnicalMD(query, answer, sources);
      case "swot": return generateSWOTMD(query, answer, sources);
    }
  }, [template, query, answer, sources]);

  const filename = `${template}-report-${query.slice(0, 40).replace(/[^a-zA-Z0-9]/g, "-")}`;

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [md]);

  const handleExportMarkdown = useCallback(() => {
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${filename}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }, [md, filename]);

  const handleExportHTML = useCallback(() => {
    const html = generateHTML(md, query, includeCover, includeToc);
    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${filename}.html`;
    a.click();
    URL.revokeObjectURL(url);
  }, [md, query, includeCover, includeToc, filename]);

  const handlePrint = useCallback(() => {
    const html = generateHTML(md, query, includeCover, includeToc);
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 500);
  }, [md, query, includeCover, includeToc]);

  if (!hasAnswer) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      className="mb-4 space-y-2"
    >
      <div className="flex flex-wrap items-center gap-1.5">
        <span className="mr-1 text-[10px] font-medium text-[var(--text-muted)]">
          <FileText className="mr-1 inline h-3 w-3" />
          Export
        </span>

        {TEMPLATES.map((t) => (
          <button
            key={t.key}
            onClick={() => { setTemplate(t.key); setShowOptions(true); }}
            className={cn(
              "inline-flex items-center gap-1.5 rounded-lg border px-2.5 py-1.5 text-[10px] font-medium transition-colors",
              template === t.key
                ? "border-cyan-400/30 bg-cyan-500/10 text-cyan-300"
                : "border-white/[0.06] text-[var(--text-secondary)] hover:bg-white/[0.06] hover:text-[var(--text-primary)]",
            )}
            title={t.description}
          >
            <t.icon className="h-3 w-3" />
            {t.label}
          </button>
        ))}

        <div className="ml-auto flex gap-1">
          <button
            onClick={handleCopy}
            className="inline-flex items-center gap-1.5 rounded-lg border border-white/[0.06] px-2.5 py-1.5 text-[10px] font-medium text-[var(--text-secondary)] transition-colors hover:bg-white/[0.06] hover:text-[var(--text-primary)]"
          >
            {copied ? (
              <><Check className="h-3 w-3 text-emerald-400" /> Copied</>
            ) : (
              <><ClipboardCopy className="h-3 w-3" /> Copy</>
            )}
          </button>
          <button onClick={handleExportMarkdown} className="inline-flex items-center gap-1.5 rounded-lg border border-white/[0.06] px-2.5 py-1.5 text-[10px] font-medium text-[var(--text-secondary)] transition-colors hover:bg-white/[0.06] hover:text-[var(--text-primary)]">
            <FileDown className="h-3 w-3" /> .md
          </button>
          <button onClick={handleExportHTML} className="inline-flex items-center gap-1.5 rounded-lg border border-white/[0.06] px-2.5 py-1.5 text-[10px] font-medium text-[var(--text-secondary)] transition-colors hover:bg-white/[0.06] hover:text-[var(--text-primary)]">
            <FileDown className="h-3 w-3" /> .html
          </button>
          <button onClick={handlePrint} className="inline-flex items-center gap-1.5 rounded-lg border border-white/[0.06] px-2.5 py-1.5 text-[10px] font-medium text-[var(--text-secondary)] transition-colors hover:bg-white/[0.06] hover:text-[var(--text-primary)]">
            <Printer className="h-3 w-3" /> Print
          </button>
        </div>
      </div>

      <AnimatePresence>
        {showOptions && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            className="flex flex-wrap items-center gap-3 overflow-hidden rounded-lg border border-white/[0.06] bg-white/[0.02] px-3 py-2"
          >
            <span className="text-[9px] font-medium text-[var(--text-muted)]">Options:</span>
            <label className="flex cursor-pointer items-center gap-1.5">
              <input
                type="checkbox"
                checked={includeCover}
                onChange={(e) => setIncludeCover(e.target.checked)}
                className="h-3 w-3 rounded border-white/[0.1] bg-white/[0.04] text-cyan-500"
              />
              <span className="text-[10px] text-[var(--text-secondary)]">Cover page</span>
            </label>
            <label className="flex cursor-pointer items-center gap-1.5">
              <input
                type="checkbox"
                checked={includeToc}
                onChange={(e) => setIncludeToc(e.target.checked)}
                className="h-3 w-3 rounded border-white/[0.1] bg-white/[0.04] text-cyan-500"
              />
              <span className="text-[10px] text-[var(--text-secondary)]">Table of Contents</span>
            </label>
            <span className="text-[8px] text-[var(--text-muted)]">
              {template === "technical" ? "Sections auto-linked" : template === "swot" ? "Auto-classified by keyword" : "Condensed format"}
            </span>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
